#define IDI_MAIN        101
#define IDD_MAIN        102
#define IDD_ABOUT       103
#define IDR_ACCELERATOR 104

#define IDC_COMMAND 1000
#define IDC_RUNNOW  1001
#define IDC_TIME    1002
#define IDC_START   1006
#define IDC_CLOSE   1007
#define IDC_BEEP    1008

#define IDM_ABOUT   1009

#define IDC_BUILD   1010
#define IDC_LICENSE 1011

#define IDS_TITLE           200
#define IDS_ABOUT           201
#define IDS_START           202
#define IDS_STOP            203
#define IDS_TIME_ELAPSED    204

#define IDS_REQUIRES_NT     205
#define IDS_COMMAND_ERROR   206

#define IDS_UNKNOWNMSG      207

#define IDS_ERRORMSG            300
#define IDS_NOMEMORYMSG         IDS_ERRORMSG+8
#define IDS_FILENOTFOUNDMSG     IDS_ERRORMSG+2
#define IDS_BADPATHMSG          IDS_ERRORMSG+3
#define IDS_MANYOPENFILESMSG    IDS_ERRORMSG+4
#define IDS_NOMEMORYMSG         IDS_ERRORMSG+8
#define IDS_NEWWINDOWSMSG       IDS_ERRORMSG+10
#define IDS_EXECERRTITLE        IDS_ERRORMSG+11
#define IDS_OS2APPMSG           IDS_ERRORMSG+12
#define IDS_MULTIPLEDSMSG       IDS_ERRORMSG+16
#define IDS_PMODEONLYMSG        IDS_ERRORMSG+18
#define IDS_COMPRESSEDEXE       IDS_ERRORMSG+19
#define IDS_INVALIDDLL          IDS_ERRORMSG+20
#define IDS_SHAREERROR          IDS_ERRORMSG+26
#define IDS_ASSOCINCOMPLETE     IDS_ERRORMSG+27
#define IDS_DDEFAIL             IDS_ERRORMSG+29
#define IDS_NOASSOCMSG          IDS_ERRORMSG+31
